//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.01 at 10:56:37 PM CET 
//


package cz.wicketstuff.boss.flow.builder.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Similar to 'if' statement in java programming
 * 				language.
 * 			
 * 
 * <p>Java class for ConditionStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionStateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.wicketstuff.cz/p/boss-flow/flowXmlModel}VirtualStateType">
 *       &lt;sequence>
 *         &lt;element name="conditionExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thenTransition" type="{http://www.wicketstuff.cz/p/boss-flow/flowXmlModel}TransitionIdentifierType"/>
 *         &lt;element name="elseTransition" type="{http://www.wicketstuff.cz/p/boss-flow/flowXmlModel}TransitionIdentifierType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionStateType", propOrder = {
    "conditionExpression",
    "thenTransition",
    "elseTransition"
})
public class ConditionStateType
    extends VirtualStateType
{

    @XmlElement(required = true)
    protected String conditionExpression;
    @XmlElement(required = true)
    protected TransitionIdentifierType thenTransition;
    @XmlElement(required = true)
    protected TransitionIdentifierType elseTransition;

    /**
     * Gets the value of the conditionExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionExpression() {
        return conditionExpression;
    }

    /**
     * Sets the value of the conditionExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionExpression(String value) {
        this.conditionExpression = value;
    }

    /**
     * Gets the value of the thenTransition property.
     * 
     * @return
     *     possible object is
     *     {@link TransitionIdentifierType }
     *     
     */
    public TransitionIdentifierType getThenTransition() {
        return thenTransition;
    }

    /**
     * Sets the value of the thenTransition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransitionIdentifierType }
     *     
     */
    public void setThenTransition(TransitionIdentifierType value) {
        this.thenTransition = value;
    }

    /**
     * Gets the value of the elseTransition property.
     * 
     * @return
     *     possible object is
     *     {@link TransitionIdentifierType }
     *     
     */
    public TransitionIdentifierType getElseTransition() {
        return elseTransition;
    }

    /**
     * Sets the value of the elseTransition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransitionIdentifierType }
     *     
     */
    public void setElseTransition(TransitionIdentifierType value) {
        this.elseTransition = value;
    }

}
