//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.29 at 11:31:07 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wicketstuff.cz/p/boss-flow/flowXmlModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.wicketstuff.boss.flow.builder.xml.jaxb;
