//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:10:40 AM CEST 
//


package cz.wicketstuff.boss.flow.builder.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transition" type="{http://www.etnetera.com/boss/flow/xmlModel}TransitionIdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.etnetera.com/boss/flow/xmlModel}IdentifierAttributeGroup"/>
 *       &lt;attribute name="finalState" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="startState" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="requireStateData" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="stateValidatable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="persistableState" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateType", propOrder = {
    "transition"
})
@XmlSeeAlso({
    VirtualStateType.class,
    RealStateType.class
})
public class StateType {

    protected List<TransitionIdentifierType> transition;
    @XmlAttribute(name = "finalState")
    protected Boolean finalState;
    @XmlAttribute(name = "startState")
    protected Boolean startState;
    @XmlAttribute(name = "requireStateData")
    protected Boolean requireStateData;
    @XmlAttribute(name = "stateValidatable")
    protected Boolean stateValidatable;
    @XmlAttribute(name = "persistableState")
    protected Boolean persistableState;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransitionIdentifierType }
     * 
     * 
     */
    public List<TransitionIdentifierType> getTransition() {
        if (transition == null) {
            transition = new ArrayList<TransitionIdentifierType>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the finalState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFinalState() {
        if (finalState == null) {
            return false;
        } else {
            return finalState;
        }
    }

    /**
     * Sets the value of the finalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFinalState(Boolean value) {
        this.finalState = value;
    }

    /**
     * Gets the value of the startState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStartState() {
        if (startState == null) {
            return false;
        } else {
            return startState;
        }
    }

    /**
     * Sets the value of the startState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartState(Boolean value) {
        this.startState = value;
    }

    /**
     * Gets the value of the requireStateData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRequireStateData() {
        if (requireStateData == null) {
            return false;
        } else {
            return requireStateData;
        }
    }

    /**
     * Sets the value of the requireStateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequireStateData(Boolean value) {
        this.requireStateData = value;
    }

    /**
     * Gets the value of the stateValidatable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStateValidatable() {
        if (stateValidatable == null) {
            return false;
        } else {
            return stateValidatable;
        }
    }

    /**
     * Sets the value of the stateValidatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStateValidatable(Boolean value) {
        this.stateValidatable = value;
    }

    /**
     * Gets the value of the persistableState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPersistableState() {
        if (persistableState == null) {
            return false;
        } else {
            return persistableState;
        }
    }

    /**
     * Sets the value of the persistableState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPersistableState(Boolean value) {
        this.persistableState = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
