//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.03 at 11:50:19 PM CEST 
//


package cz.wicketstuff.boss.flow.builder.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Extended transition identifier that can mark if the transition is default as next or previous transition. Application logic needn't to define it in the code, it is also possible to use XML to configure.
 * 
 * <p>Java class for TransitionIdentifierDefaultsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransitionIdentifierDefaultsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.wicketstuff.cz/p/boss-flow/flowXmlModel}TransitionIdentifierType">
 *       &lt;attribute name="previous" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="next" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="defaultPrevious" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="defaultNext" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransitionIdentifierDefaultsType")
public class TransitionIdentifierDefaultsType
    extends TransitionIdentifierType
{

    @XmlAttribute(name = "previous")
    protected Boolean previous;
    @XmlAttribute(name = "next")
    protected Boolean next;
    @XmlAttribute(name = "defaultPrevious")
    protected Boolean defaultPrevious;
    @XmlAttribute(name = "defaultNext")
    protected Boolean defaultNext;

    /**
     * Gets the value of the previous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPrevious() {
        if (previous == null) {
            return false;
        } else {
            return previous;
        }
    }

    /**
     * Sets the value of the previous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrevious(Boolean value) {
        this.previous = value;
    }

    /**
     * Gets the value of the next property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNext() {
        if (next == null) {
            return false;
        } else {
            return next;
        }
    }

    /**
     * Sets the value of the next property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNext(Boolean value) {
        this.next = value;
    }

    /**
     * Gets the value of the defaultPrevious property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDefaultPrevious() {
        if (defaultPrevious == null) {
            return false;
        } else {
            return defaultPrevious;
        }
    }

    /**
     * Sets the value of the defaultPrevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultPrevious(Boolean value) {
        this.defaultPrevious = value;
    }

    /**
     * Gets the value of the defaultNext property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDefaultNext() {
        if (defaultNext == null) {
            return false;
        } else {
            return defaultNext;
        }
    }

    /**
     * Sets the value of the defaultNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultNext(Boolean value) {
        this.defaultNext = value;
    }

}
