//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:10:40 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.etnetera.com/boss/flow/xmlModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.etnetera.boss.flow.builder.xml.jaxb;
